services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/db

  python:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/code
    network_mode: service:mongodb
    command: sleep infinity
